// USERS
GET http://localhost:4000/api/v1/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBbGV4IiwiZW1haWwiOiJhbGV4QGdtYWlsLmNvbSIsImlhdCI6MTYyNzcxMDM1MywiZXhwIjoxNjI3NzEwNDEzfQ.7k9tbGbyCXqWfIZccajYLnwR1trt77aKr2zjxXQUDZQ
###
POST http://localhost:4000/api/v1/users
content-type: application/json

{
  "first_name": "Max", 
  "last_name": "Manukyan", 
  "email": "max@gmail.com", 
  "password": "secret"
}
###
POST http://localhost:4000/api/v1/sessions
content-type: application/json

{"username": "Alex"}
###
DELETE http://localhost:4000/api/v1/sessions
###
GET http://localhost:4000/api/v1/sessions

// LOTS

###
GET http://localhost:4000/api/v1/lots
###
GET http://localhost:4000/api/v1/lots?user_id=1
###
POST http://localhost:4000/api/v1/lots
content-type: application/json

{"owner_id": 1, "title": "lot1", "description": "description"}
###
PATCH http://localhost:4000/api/v1/lots/1/offers/1
content-type: application/json

{"is_accepted": false}



// OFFERS
###
GET http://localhost:4000/api/v1/offers

###
GET http://localhost:4000/api/v1/offers?user_id=1
 
###
POST http://localhost:4000/api/v1/offers
content-type: application/json

{"owner_id": 1, "lot_id": 1, "title": "offer1", "description": "description"}

###
GET http://localhost:4000/api/v1/users/1/lots

###
GET http://localhost:4000/api/v1/users/1/offers